#!/bin/sh

# loads every other file in this same directory
currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
binDir="$currentDir/../../bin"

while read file
do
  file=$currentDir/scripts/$file.sh
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done <<EOM
aliases
dreload
exports
history
taskwarrior
vim
workspace
EOM

# makes tools under dotfiles/environments/bin available
export PATH="$binDir:$PATH"

unset file;
unset currentDir;
unset binDir;
