#!/bin/sh

# loads every other file in this same directory
currentDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

while read file
do
  file=$currentDir/scripts/$file.sh
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done <<EOM
aliases
editor
exports
history
workspace
EOM

unset file;
unset currentDir;
