#!/bin/sh
set -o vi

export JAVA_HOME=$(/usr/libexec/java_home)
export ECLIM_HOME='/Applications/Eclipse\ Java.app/Contents/Eclipse/plugins/org.eclim_2.7.0'
export PATH=$HOME/bin:$PATH

# alias workspace="pushd $HOME/workspace"
# alias wikis="pushd $HOME/wikis"
# alias downloads="pushd /Users/daplay/Downloads"
# alias daplay="tmux new-session -s daplay vim -c \"call vimwiki#base#goto_index(1)\""
# alias family="tmux new-session -s daplay vim -c \"call vimwiki#base#goto_index(2)\""
# alias reload="source $HOME/.bashrc"
# # alias start_eclimd="./"

