#!/bin/sh

set -e

function usage() {
	echo "Usage: $0 DIRECTORY [update|sync]" >&2
	exit 1
}

if [ "$#" -lt 1  ] || ! [ -d "$1"  ]; then
  usage
fi

readonly directory=$1
readonly today=$(date +'%Y-%m-%d')

# does the pulling part of the problem
function doUpdate() {
	# echo "doing update"
  readonly lockFileName="$directory/$today.pulled"

  if [ ! -f "$lockFileName" ]
  then
     touch $lockFileName
  else 
    # can't this message from generating a new email
    # echo "$0: File '$lockFileName' exists, update won't take place as it, for today, happen already."
    return 0
  fi

  set -x

  git -C $directory checkout master 1>/dev/null
  git -C $directory pull 1>/dev/null

  set +x

	# To add changes in another branch adds the complexity of
	# Merging in yesterdays branches
  # echo git -C $directory checkout -b $today
}

# does the pushing part of the problem
function doSync() {
	local readonly now=$(date +'%Y-%m-%d %HH:%MM')

  set -x

  git -C $directory add --all 1>/dev/null
  git -C $directory commit -m"Auto commit at: $now" 1>/dev/null
  git -C $directory push origin 1>/dev/null

  set +x
}

# removes locks that aren't from today
function removeLocks() {
  find $directory -type f -name '*.pulled' ! -name "$today.pulled" -delete
}

if [ "$#" -eq 2  ]; then
	subcommand=$2

	if [ "x$subcommand" = "xupdate"  ]; then
		doUpdate
	elif [ "x$subcommand" = "xsync"  ]; then
		doSync
	fi
else
  usage
fi

removeLocks
