#!/bin/sh

set -x

function syncWiki() {
  pushd $VIMWIKI
  git add --all .
  git commit -m"sync at: $(date)"
  git push origin
  popd
}

function syncDotfiles() {
  pushd $DOTFILES
  git add --all .
  git commit -m"sync at: $(date)"
  git push origin
  popd
}

syncWiki
syncDotfiles
