#!/bin/sh
#
# `dct` is short for `daniel's current ticket`
#
# I usually have branch names like: SK-1231_featureY, IPD-12312_featureX, etc...
# this utility outputs the ticket name if any

branch=$(git branch \
	| grep '*' \
	| sed -Ee 's/^[* ]+//' \
	| sed -E -e 's/^ \+//' \
	| sed -E -e 's/ \+$//')

ticket=$(echo $branch \
	| cut -d_ -f1 \
	| sed -E -e 's/^ \+//' \
	| sed -E -e 's/ \+$//')

echo "$ticket"

if [ -x "$(command -v pbcopy)"  ]; then
	echo $ticket | pbcopy
	echo "ticket: '$ticket' has been copied to your clipboard"
else
  echo "$ticket"
fi

