# Modernized tmux config (prefix C-a)

set -g prefix C-a
bind C-a send-prefix

set-option -g renumber-windows on
set -g automatic-rename on
set -g automatic-rename-format "#(basename #{pane_current_path})"
set -g mouse on
set -sg escape-time 10
set -g base-index 1
setw -g pane-base-index 1
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

bind-key + command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key * command-prompt -p "send pane to:"  "join-pane -t '%%'"

unbind [
bind Escape copy-mode
setw -g mode-keys vi
unbind p
bind p paste-buffer

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi V send -X rectangle-toggle

setw -g monitor-activity on
set -g visual-activity on

set -g status-fg white
set -g status-bg black
setw -g window-status-style fg=cyan,bg=default,dim
setw -g window-status-current-style fg=white,bg=red,bright
set -g pane-border-style fg=green,bg=black
set -g pane-active-border-style fg=white,bg=yellow
set -g message-style fg=white,bg=black,bright
set -g status-left-length 40
set -g status-left "#[fg=green]#S #[fg=yellow]#I #[fg=cyan]#P"
set -g status-right "#[fg=red]#(cd #{pane_current_path}; git rev-parse --abbrev-ref HEAD 2>/dev/null) #[fg=cyan]%d %b %R"
set -g status-interval 60
set -g status-justify centre

set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
