#!/usr/bin/env bash
# Shell module: inject a small stub that sources this repo.

set -euo pipefail

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../../lib/common.sh
source "$MODULE_DIR/../../lib/common.sh"
# shellcheck source=../../lib/detect.sh
source "$MODULE_DIR/../../lib/detect.sh"

install_shell() {
  local shell stub
  shell="$(detect_shell)"
  stub="$HOME/.dotfiles.bashrc"

  mkdir -p "$(dirname "$stub")"
  cat > "$stub" <<EOF
# Generated by dotfiles shell module — do not edit by hand.
export DOTFILES="$DOTFILES_ROOT"
source "\$DOTFILES/modules/shell/bashrc"
EOF
  ok "wrote $stub"

  case "$shell" in
    zsh)
      ensure_line_in_file "source \"$HOME/.dotfiles.bashrc\"" "$HOME/.zshrc"
      ;;
    bash)
      ensure_line_in_file "source \"$HOME/.dotfiles.bashrc\"" "$HOME/.bashrc"
      if [[ "$(detect_os)" == "macos" ]] || [[ -f "$HOME/.bash_profile" ]]; then
        ensure_line_in_file '[[ -f $HOME/.bashrc ]] && source $HOME/.bashrc' "$HOME/.bash_profile"
      fi
      ;;
    fish)
      warn "fish not fully supported yet"
      ;;
  esac

  ok "shell module installed ($shell)"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  install_shell
fi
